# Generated by Django 3.1.4 on 2021-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('industry', models.CharField(choices=[('Lodging', 'Lodging'), ('Food&Berverage', 'Food&Beverage'), ('IT', 'IT'), ('Sales', 'Sales'), ('Education', 'Education'), ('Construction', 'Construction'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Pharmaceutical', 'Pharmaceutical'), ('Finance', 'Finance'), ('Retail', 'Retail')], max_length=100)),
                ('position', models.CharField(choices=[('Front Clerk', 'Front Clerk')], max_length=100)),
                ('education', models.CharField(choices=[('High School', 'High School'), ('Associate Degree', 'Associate Degree'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree'), ('Doctoral Degree', 'Doctoral Degree')], max_length=100)),
            ],
        ),
    ]
