# Generated by Django 3.1.4 on 2021-06-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(choices=[('Other', 'Other'), ('Lodging', 'Lodging'), ('Food&Berverage', 'Food&Beverage'), ('IT', 'IT'), ('Sales', 'Sales'), ('Education', 'Education'), ('Construction', 'Construction'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Pharmaceutical', 'Pharmaceutical'), ('Finance', 'Finance'), ('Retail', 'Retail')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='position',
            field=models.CharField(choices=[('Other', 'Other'), ('Front Clerk', 'Front Clerk')], max_length=100),
        ),
    ]
