# Generated by Django 3.1.4 on 2021-06-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210606_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
